dzeppelin:
  build: ./dzeppelin
  environment:
    ZEPPELIN_PORT: 8080
    ZEPPELIN_JAVA_OPTS: >-
      -Dspark.driver.memory=1g
      -Dspark.executor.memory=2g
    MASTER: spark://192.168.0.70:7077
  ports:
    - 8000:8080
  volumes:
    - ./dzeppelin/data:/workspace/zeppelin/data
    - ./dzeppelin/notebook:/workspace/zeppelin/notebook
    - /etc/localtime:/etc/localtime:ro
    - /home/demo/workspace/spark-2.1.1-bin-hadoop2.7/conf/:/workspace/spark/conf
  extra_hosts:
    - "hp3:192.168.0.70"
